language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - echo done


# install: ./install-dependencies.sh

# language: python
# python:
#   - "3.4"
# cache: pip

# git:
#   quiet: true

# script:
#   - echo "hello world"

# language: python
# python:
#   - '3.8'
#   - '3.7'
#   - '2.7'
# jobs:
#   include:
#     - python: '3.8' # this is not strictly necessary
#       env: EXTRA_TESTS=true
#     - python: '3.7'
#       env: EXTRA_TESTS=true

# script: env $EXTRA_TESTS ./test.py $TEST_SUITE

# language: ruby

# rvm:
# - 2.0.0
# - 2.1.6

# env:
#   global:
#   - SECRET_VAR1=SECRET1
#   jobs:
#   - SECRET_VAR2=SECRET2

# jobs:
#   allow_failures:
#     - env: SECRET_VAR1=SECRET1 SECRET_VAR2=SECRET2